package com.legalhelp.petition.service;

/** The mandated legal disclaimer appended to every generated petition (CLAUDE.md domain rule #10). */
public final class PetitionDisclaimer {

    public static final String CURRENT_VERSION = "v1";

    public static final String TEXT = """
            DISCLAIMER: This document was generated by an AI system based on the information you provided \
            and category-specific templates. It is a DRAFT ONLY and does not constitute legal advice. It has \
            not been reviewed by a qualified lawyer. Before filing or relying on this document, you must have \
            it reviewed by a licensed legal professional. The platform and its operators accept no liability \
            for errors, omissions, or outcomes resulting from the use of this document.""";

    private PetitionDisclaimer() {
    }
}
